export const LINEAR_GRAVITY_NONE = 0
export const LINEAR_GRAVITY_LEFT = 1
export const LINEAR_GRAVITY_TOP = 2
export const LINEAR_GRAVITY_RIGHT = 3
export const LINEAR_GRAVITY_BOTTOM = 4
export const LINEAR_GRAVITY_CENTER_VERTICAL = 5
export const LINEAR_GRAVITY_CENTER_HORIZONTAL = 6

//RelativeAlign
export const RELATIVE_ALIGN_NONE = 0
export const RELATIVE_ALIGN_PARENT_TOP_LEFT = 1
export const RELATIVE_ALIGN_PARENT_TOP_CENTER_HORIZONTAL = 2
export const RELATIVE_ALIGN_PARENT_TOP_RIGHT = 3
export const RELATIVE_ALIGN_PARENT_LEFT_CENTER_VERTICAL = 4
export const RELATIVE_ALIGN_PARENT_CENTER = 5
export const RELATIVE_ALIGN_PARENT_RIGHT_CENTER_VERTICAL = 6
export const RELATIVE_ALIGN_PARENT_LEFT_BOTTOM = 7
export const RELATIVE_ALIGN_PARENT_BOTTOM_CENTER_HORIZONTAL = 8
export const RELATIVE_ALIGN_PARENT_RIGHT_BOTTOM = 9

export const RELATIVE_ALIGN_LOCATION_ABOVE_LEFT = 10
export const RELATIVE_ALIGN_LOCATION_ABOVE_CENTER = 11
export const RELATIVE_ALIGN_LOCATION_ABOVE_RIGHT = 12

export const RELATIVE_ALIGN_LOCATION_LEFT_TOP = 13
export const RELATIVE_ALIGN_LOCATION_LEFT_CENTER = 14
export const RELATIVE_ALIGN_LOCATION_LEFT_BOTTOM = 15

export const RELATIVE_ALIGN_LOCATION_RIGHT_TOP = 16
export const RELATIVE_ALIGN_LOCATION_RIGHT_CENTER = 17
export const RELATIVE_ALIGN_LOCATION_RIGHT_BOTTOM = 18

export const RELATIVE_ALIGN_LOCATION_BELOW_TOP = 19
export const RELATIVE_ALIGN_LOCATION_BELOW_CENTER = 20
export const RELATIVE_ALIGN_LOCATION_BELOW_BOTTOM = 21
